### ISSUE TITLE
Improve menu hover

### ISSUE THREAD

**Issue by blemaire** [Damscreb/cdf-thal#10]
I noticed a strange behaviour when hovering the menu items (see gif below
![cdf menu hover](https://user-images.githubusercontent.com/7140322/144090568-befb760e-cbef-4a7c-8e2f-7da1b60d0b7b.gif)
)

Indeed each element (text and line) change color too many times leading to difficult to understand behaviour.

I would recommend removing the colour change on the line so that it is always bleu and only the text changes on hover.

**Comment by Damscreb** [comment]
I like the idea to change both colors of title + line<br/>I'm gonna try to fix it, if i can't i wont change the color of the line

**Comment by Damscreb** [comment]
Done
