### ISSUE TITLE
Cast

### ISSUE THREAD

**Issue by Damscreb** [Damscreb/cdf-thal#5]
Add a new "Cast" page with a list of differents casters<br/>The goal is to be able to click on a name which make change the URL of the twitch integration with the channel of the desired caster<br/>Extra : Be able to know if the streamers in the list are online or not with a little green round next to their name

**Comment by blemaire** [comment]
Do you mind If I try this issue ?

**Comment by Damscreb** [comment]
Just go :)

**Comment by blemaire** [comment]
@Damscreb happy with the wording and the icon like this: 
![image](https://user-images.githubusercontent.com/7140322/144098790-04577951-1d6e-4904-b302-cb2ab146f10f.png)
![image](https://user-images.githubusercontent.com/7140322/144098826-f788ee88-63fc-482c-8b1c-053da8e8959d.png)
![image](https://user-images.githubusercontent.com/7140322/144098847-9f6cafe3-f4a9-4138-bdcf-fbf8ec57d75c.png)

**Comment by Damscreb** [comment]
🤩Only need to add the links of colem and ice and lets gooo :D

**Comment by blemaire** [comment]
fixed by #12
